# Generated by Django 3.2 on 2021-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='image',
            field=models.ImageField(default='default.tif', upload_to='images'),
        ),
    ]
