# Generated by Django 3.2 on 2021-04-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0003_remove_drop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotter.drop')),
            ],
        ),
    ]
