# Generated by Django 3.2 on 2021-04-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0005_auto_20210429_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropimage',
            name='image_type',
            field=models.CharField(choices=[('Cropped', 'Cropped'), ('Fitted', 'Fitted'), ('Full', 'Full'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
