# Generated by Django 3.2 on 2021-04-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0006_dropimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropimage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
