# Generated by Django 3.2.5 on 2021-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0009_technique_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='url',
        ),
        migrations.AddField(
            model_name='technique',
            name='detailed_description',
            field=models.CharField(default='Detailed description coming soon!', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
