# Generated by Django 3.2.5 on 2021-09-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0010_auto_20210831_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='technique',
            name='detailed_description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roughness', models.CharField(max_length=100)),
                ('mass_before', models.CharField(max_length=100)),
                ('mass_after', models.CharField(max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plotter.material')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plotter.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plotter.materialtype'),
        ),
    ]
