# Generated by Django 3.2.5 on 2021-09-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0011_auto_20210902_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='type',
        ),
    ]
