# Generated by Django 3.2.5 on 2021-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0013_auto_20210902_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
        migrations.AddField(
            model_name='sample',
            name='number',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
