# Generated by Django 3.2.5 on 2021-09-07 20:25

from django.db import migrations, models
import plotter.models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0014_auto_20210907_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=plotter.models.drop_upload_dir)),
            ],
        ),
    ]
