# Generated by Django 3.2.5 on 2021-09-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0015_sampleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleimage',
            name='sample',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='plotter.sample'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='number',
            field=models.IntegerField(),
        ),
    ]
