# Generated by Django 3.2.5 on 2021-09-07 20:38

from django.db import migrations, models
import django.db.models.deletion
import plotter.models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0016_auto_20210907_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleimage',
            name='image',
            field=models.ImageField(upload_to=plotter.models.sample_upload_dir),
        ),
        migrations.CreateModel(
            name='TechniqueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=plotter.models.technique_upload_dir)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotter.technique')),
            ],
        ),
    ]
