# Generated by Django 3.2.5 on 2021-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0017_auto_20210907_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='substrate',
        ),
        migrations.AddField(
            model_name='technique',
            name='link',
            field=models.CharField(default='https://mrl.illinois.edu/facilities/equipment/keyence-vk-x1000-3d-laser-scanning-confocal-microscope', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Substrate',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
