# Generated by Django 3.2.5 on 2021-09-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0018_auto_20210909_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueimage',
            name='caption',
            field=models.TextField(default='The Keyence VK-X1000 3D Laser Scanning Confocal Microscope located at MRL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techniqueimage',
            name='source',
            field=models.TextField(default='https://mrl.illinois.edu/facilities/equipment/keyence-vk-x1000-3d-laser-scanning-confocal-microscope'),
            preserve_default=False,
        ),
    ]
