# Generated by Django 3.2 on 2021-04-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_drop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='image',
        ),
    ]
